POST http://localhost:3000/api/photos HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwucGwiLCJpYXQiOjE2ODQ2NTg2NzIsImV4cCI6MTY4NDY2MjI3Mn0.xW7zuNi4jHD0p34zi8mOtVcZp3k8Iv2ev0DDXh0RFRs
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

nazwa_albumu
------FormBoundary1234

### GET - pobierz wszystkie dane
GET http://localhost:3000/api/photos HTTP/1.1
###

GET http://localhost:3000/api/photos/1684259792095 HTTP/1.1

### PATCH - updatuj wg id
PATCH http://localhost:3000/api/photos HTTP/1.1
content-type: application/json

{
 "id": 1683306249379,
 "history": "changed"
}

### Delete request
DELETE  http://localhost:3000/api/photos/1683279872453 HTTP/1.1

### ADD TAG
PATCH http://localhost:3000/api/photos/tags HTTP/1.1
content-type: application/json

{
 "id": 1684259792095,
 "tagId": 0
}

### ADD MANY TAGS
PATCH http://localhost:3000/api/photos/tags/mass HTTP/1.1
content-type: application/json

{
 "id": 1684259792095,
 "tagId": [3,4,5]
}

### GET PHOTO TAGS
GET http://localhost:3000/api/photos/tags/1684259792095 HTTP/1.1

###
POST http://localhost:3000/api/photos/getPicture HTTP/1.1

{
    
}